import type { ClimbGroup } from "./types"

export const climbGroups: ClimbGroup[] = [
  {
    id: "feb-1-2025",
    route: "8 Day Lemosho route",
    arrivalDate: "Feb 1, 2025",
    departureDate: "Feb 9, 2025",
    price: 2980,
    totalSpaces: 8,
    spacesLeft: 5,
    difficulty: "Moderate",
    duration: 8,
    description:
      "The Lemosho route is considered one of the most scenic trails on Kilimanjaro, granting panoramic vistas on various sides of the mountain.",
  },
  {
    id: "feb-5-2025",
    route: "7 Day Machame route",
    arrivalDate: "Feb 5, 2025",
    departureDate: "Feb 12, 2025",
    price: 2540,
    totalSpaces: 10,
    spacesLeft: 5,
    difficulty: "Challenging",
    duration: 7,
    description:
      'Known as the "Whiskey Route," Machame is a popular path that offers stunning views through diverse landscapes.',
  },
  {
    id: "feb-10-2025",
    route: "8 Day Lemosho route",
    arrivalDate: "Feb 10, 2025",
    departureDate: "Feb 18, 2025",
    price: 2980,
    totalSpaces: 8,
    spacesLeft: 7,
    difficulty: "Moderate",
    duration: 8,
    description:
      "The Lemosho route is considered one of the most scenic trails on Kilimanjaro, granting panoramic vistas on various sides of the mountain.",
  },
  {
    id: "feb-26-2025",
    route: "7 Day Machame route",
    arrivalDate: "Feb 26, 2025",
    departureDate: "Mar 5, 2025",
    price: 2540,
    totalSpaces: 10,
    spacesLeft: 7,
    difficulty: "Challenging",
    duration: 7,
    description:
      'Known as the "Whiskey Route," Machame is a popular path that offers stunning views through diverse landscapes.',
  },
  {
    id: "mar-1-2025",
    route: "6 Day Machame route (Full Moon climb)",
    arrivalDate: "Mar 1, 2025",
    departureDate: "Mar 7, 2025",
    price: 2380,
    totalSpaces: 12,
    spacesLeft: 10,
    difficulty: "Challenging",
    duration: 6,
    description: "Experience the magic of summiting under a full moon with this special Machame route climb.",
  },
  {
    id: "mar-15-2025",
    route: "7 Day Machame route (Full Moon climb)",
    arrivalDate: "Mar 15, 2025",
    departureDate: "Mar 22, 2025",
    price: 2540,
    totalSpaces: 10,
    spacesLeft: 10,
    difficulty: "Challenging",
    duration: 7,
    description: "Experience the magic of summiting under a full moon with this special Machame route climb.",
  },
  {
    id: "mar-20-2025",
    route: "6 Day Rongai route (Full Moon climb)",
    arrivalDate: "Mar 20, 2025",
    departureDate: "Mar 26, 2025",
    price: 2380,
    totalSpaces: 8,
    spacesLeft: 5,
    difficulty: "Moderate",
    duration: 6,
    description:
      "The only route that approaches Kilimanjaro from the north, offering a unique perspective and full moon summit experience.",
  },
  {
    id: "apr-1-2025",
    route: "8 Day Lemosho route",
    arrivalDate: "Apr 1, 2025",
    departureDate: "Apr 9, 2025",
    price: 2980,
    totalSpaces: 8,
    spacesLeft: 8,
    difficulty: "Moderate",
    duration: 8,
    description:
      "The Lemosho route is considered one of the most scenic trails on Kilimanjaro, granting panoramic vistas on various sides of the mountain.",
  },
]

